In [3]:
import pandas as pd

df = pd.read_csv('/content/watchlist.csv')

df

           Date               Name  Year        Letterboxd URI
0    2023-12-24             Psycho  1960  https://boxd.it/2ab2
1    2023-12-24       Pulp Fiction  1994  https://boxd.it/29Pq
2    2023-12-24    The Truman Show  1998  https://boxd.it/18U8
3    2023-12-24         The Matrix  1999  https://boxd.it/2a1m
4    2023-12-24           Scarface  1983  https://boxd.it/2b7g
..          ...                ...   ...                   ...
137  2026-04-23      The Brutalist  2024  https://boxd.it/k4BO
138  2026-04-29    A Different Man  2024  https://boxd.it/BoEC
139  2026-04-29  Oslo, August 31st  2011  https://boxd.it/2xQC
140  2026-05-17           Hardware  1990  https://boxd.it/1Uas
141  2026-05-19          Obsession  2025  https://boxd.it/PNqo

[142 rows x 4 columns]

In [35]:
import requests
from bs4 import BeautifulSoup
import re

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

for index, row in df.iterrows():
  url = row['Letterboxd URI']
  response = requests.get(url, headers=headers)
  soup = BeautifulSoup(response.text, 'html.parser')
  try:
    rating = soup.find("meta", {"name": "twitter:data2"})
    duration = soup.find("p", class_="text-link text-footer")
    mins = re.search(r'(\d+)\xa0mins', duration.get_text())
    df.at[index, 'Rating'] = rating["content"][:4]
    df.at[index, 'Duration'] = mins.group(1)
  except Exception as e:
    print("Error:", e)
df

Error: 'NoneType' object is not subscriptable
Error: 'NoneType' object is not subscriptable
Error: 'NoneType' object is not subscriptable
Error: 'NoneType' object is not subscriptable

           Date               Name  Year        Letterboxd URI Rating Duration
0    2023-12-24             Psycho  1960  https://boxd.it/2ab2   4.31      109
1    2023-12-24       Pulp Fiction  1994  https://boxd.it/29Pq   4.24      154
2    2023-12-24    The Truman Show  1998  https://boxd.it/18U8   4.22      103
3    2023-12-24         The Matrix  1999  https://boxd.it/2a1m   4.18      136
4    2023-12-24           Scarface  1983  https://boxd.it/2b7g   4.15      170
..          ...                ...   ...                   ...    ...      ...
137  2026-04-23      The Brutalist  2024  https://boxd.it/k4BO   3.89      215
138  2026-04-29    A Different Man  2024  https://boxd.it/BoEC   3.80      112
139  2026-04-29  Oslo, August 31st  2011  https://boxd.it/2xQC   4.10       90
140  2026-05-17           Hardware  1990  https://boxd.it/1Uas   3.26       93
141  2026-05-19          Obsession  2025  https://boxd.it/PNqo   4.20      108

[142 rows x 6 columns]